Fix missing devserver.ports pillar on ysul
Summary:
While applying the Salt state roles/devserver on ysul for T2315, the deployment failed with the following error:

```
Rendering SLS 'base:roles/devserver/.poudriere.config' failed: Jinja variable
'salt.utils.context.NamespacedDictWrapper object'
has no attribute 'poudriere'
```

This was caused by ysul not being assigned to the devserver.ports pillar in pillar/top.sls.

So this review declare devserver.ports for ysul in pillar top.sls to expose poudriere settings

Reviewers: dereckson, Duranzed

Reviewed By: dereckson

Subscribers: Duranzed, dereckson

Differential Revision: https://devcentral.nasqueron.org/D4091